export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  VENTA_DUPLICADA: 'VENTA_DUPLICADA',
  BONO_INVALIDO: 'BONO_INVALIDO',
  BONO_NO_PERTENECE: 'BONO_NO_PERTENECE',
  COMPRA_MINIMA_NO_CUMPLIDA: 'COMPRA_MINIMA_NO_CUMPLIDA',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

